name: WIS2 Manual

on:
  push:
    branches:
    - main

env:
  FILE_BASENAME: wis2-manual-APPROVED

jobs:
  build-wis2-manual:
    name: Generate documentation
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update -y \
          && sudo apt-get install -y pandoc \
          && sudo gem install asciidoctor asciidoctor-pdf
      - name: checkout repository
        uses: actions/checkout@v3
      - name: build documentation
        run: |
          mkdir -p /tmp/wis2-manual/manual \
          && cd manual \
          && asciidoctor --trace -a stylesheet=css/wmo-asciidoc.cs -o /tmp/wis2-manual/manual/${FILE_BASENAME}.html index.adoc \
          && asciidoctor --trace --backend docbook --out-file - index.adoc | pandoc --from docbook --to docx --output /tmp/wis2-manual/manual/${FILE_BASENAME}.docx \
          && asciidoctor --trace -r asciidoctor-pdf --trace -b pdf -o /tmp/wis2-manual/manual/${FILE_BASENAME}.pdf index.adoc \
          && cp images/*.{jpg,png} /tmp/wis2-manual/manual/images \
          && cd ..
      - name: checkout gh-pages branch
        uses: actions/checkout@v3
        with:
          ref: gh-pages
      - name: update gh-pages branch and publish
        run: | 
          git checkout gh-pages
          git config --global user.email "wis2-support@gmail.com"
          git config --global user.name "gh-pages GHA"
          rm -rf manual images
          mv -f /tmp/wis2-manual/* .
          git add .
          git commit -am "update WIS2 Manual build"
          git push

